// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1GSCcmvbYQ5yGUSkzPEuVS4Slc6fYZA',
    appId: '1:98009371906:web:bcab8fd75af156f8489e1b',
    messagingSenderId: '98009371906',
    projectId: 'momo-watcher',
    authDomain: 'momo-watcher.firebaseapp.com',
    storageBucket: 'momo-watcher.appspot.com',
    measurementId: 'G-PJS4ECP2C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpt3RfzFQY_zPhS9lGEFE78iOhMR9OgXw',
    appId: '1:98009371906:android:5438f15fa7ec3610489e1b',
    messagingSenderId: '98009371906',
    projectId: 'momo-watcher',
    storageBucket: 'momo-watcher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnTtZFb4LKZtXNEYe8GEG0TCHLSw9XAp4',
    appId: '1:98009371906:ios:c8cdfe18eb95ce7b489e1b',
    messagingSenderId: '98009371906',
    projectId: 'momo-watcher',
    storageBucket: 'momo-watcher.appspot.com',
    iosBundleId: 'com.example.momoWalletWatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnTtZFb4LKZtXNEYe8GEG0TCHLSw9XAp4',
    appId: '1:98009371906:ios:c8cdfe18eb95ce7b489e1b',
    messagingSenderId: '98009371906',
    projectId: 'momo-watcher',
    storageBucket: 'momo-watcher.appspot.com',
    iosBundleId: 'com.example.momoWalletWatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1GSCcmvbYQ5yGUSkzPEuVS4Slc6fYZA',
    appId: '1:98009371906:web:80feb5285bed387b489e1b',
    messagingSenderId: '98009371906',
    projectId: 'momo-watcher',
    authDomain: 'momo-watcher.firebaseapp.com',
    storageBucket: 'momo-watcher.appspot.com',
    measurementId: 'G-X0JTN8FHKT',
  );
}
