// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9Hr7MBU_2brk_9y3IH4PfzownP_YJB4',
    appId: '1:490506863605:web:c19bd84f8f7755d2acd6bc',
    messagingSenderId: '490506863605',
    projectId: 'wallet-watcher-6bd73',
    authDomain: 'wallet-watcher-6bd73.firebaseapp.com',
    storageBucket: 'wallet-watcher-6bd73.appspot.com',
    measurementId: 'G-C4XM7YLL7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1mmIPAit2uPoJ1m2NWvLccIO-2c4oko',
    appId: '1:490506863605:android:cc21f03ef2770559acd6bc',
    messagingSenderId: '490506863605',
    projectId: 'wallet-watcher-6bd73',
    storageBucket: 'wallet-watcher-6bd73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5xQdlua1fc_-4Mnmlt9LO12r8XkhtwtU',
    appId: '1:490506863605:ios:7fbdcc81acf01a6eacd6bc',
    messagingSenderId: '490506863605',
    projectId: 'wallet-watcher-6bd73',
    storageBucket: 'wallet-watcher-6bd73.appspot.com',
    iosBundleId: 'com.example.momoWalletWatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5xQdlua1fc_-4Mnmlt9LO12r8XkhtwtU',
    appId: '1:490506863605:ios:7fbdcc81acf01a6eacd6bc',
    messagingSenderId: '490506863605',
    projectId: 'wallet-watcher-6bd73',
    storageBucket: 'wallet-watcher-6bd73.appspot.com',
    iosBundleId: 'com.example.momoWalletWatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe9Hr7MBU_2brk_9y3IH4PfzownP_YJB4',
    appId: '1:490506863605:web:bbe103c22fd1b230acd6bc',
    messagingSenderId: '490506863605',
    projectId: 'wallet-watcher-6bd73',
    authDomain: 'wallet-watcher-6bd73.firebaseapp.com',
    storageBucket: 'wallet-watcher-6bd73.appspot.com',
    measurementId: 'G-J60W24ZTXY',
  );

}